# Generated by Django 4.0.5 on 2022-06-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('map', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(default='xx', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('distance', models.FloatField(null=True)),
                ('path', models.JSONField()),
                ('map', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('content', models.JSONField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.article')),
            ],
        ),
        migrations.CreateModel(
            name='CountryVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_visit', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.article')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.country')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.journey'),
        ),
    ]
