# Generated by Django 4.0.5 on 2022-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('map', 'simple_map_post'), ('map_helper', 'map_with_helper_post'), ('carousel', 'carousel_post'), ('image', 'single_image_post'), ('images', 'multi_image_post'), ('text', 'plain_text_post'), ('link', 'single_link_post'), ('accordion', 'accordion_post')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
