# Generated by Django 4.0.5 on 2022-06-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0003_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(default={}),
        ),
    ]
