# Generated by Django 4.0.5 on 2022-06-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
        migrations.AlterModelOptions(
            name='countryvisit',
            options={'verbose_name': 'посещение страны', 'verbose_name_plural': 'посещения стран'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'verbose_name': 'поездка', 'verbose_name_plural': 'поездки'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AddField(
            model_name='journey',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='Дата финиша'),
        ),
        migrations.AddField(
            model_name='journey',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='distance',
            field=models.FloatField(null=True, verbose_name='Дистанция'),
        ),
        migrations.AlterField(
            model_name='article',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='Дата финиша'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.journey', verbose_name='Поездка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='map',
            field=models.JSONField(verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(default='xx', max_length=10, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='countryvisit',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='countryvisit',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='countryvisit',
            name='latest_visit',
            field=models.DateField(verbose_name='Последнее посещение'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.FloatField(null=True, verbose_name='Дистанция'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(default=dict, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.SmallIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('map', 'simple_map_post'), ('map_helper', 'map_with_helper_post'), ('carousel', 'carousel_post'), ('image', 'single_image_post'), ('images', 'multi_image_post'), ('text', 'plain_text_post'), ('link', 'single_link_post'), ('accordion', 'accordion_post')], max_length=10, verbose_name='Тип записи'),
        ),
    ]
