# Generated by Django 4.0.5 on 2022-06-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0005_alter_article_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='map',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='journey',
            name='path',
            field=models.JSONField(default=dict),
        ),
    ]
