# Generated by Django 4.0.5 on 2022-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0006_alter_journey_map_alter_journey_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='map',
            field=models.JSONField(default=dict, null=True, verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('map', 'Блок с картой'), ('map-helper', 'Карта с подсказками'), ('carousel', 'Блок-карусель'), ('image', 'Блок с картинкой'), ('images', 'Несколько картинок'), ('link', 'Блок со ссылкой'), ('accordion', 'Блок-аккордион')], max_length=10, verbose_name='Тип записи'),
        ),
    ]
