# Generated by Django 4.0.5 on 2022-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0007_alter_article_map_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('europe', 'Европа'), ('russia', 'Россия'), ('middle-east', 'Ближний Восток'), ('far-east', 'Дальний Восток'), ('central-asia', 'Центральная Азия'), ('australia', 'Австралия'), ('north-america', 'Северная Америка'), ('south-america', 'Южная Америка'), ('africa', 'Африка'), ('etc', 'Другое')], default='etc', max_length=20),
        ),
    ]
