# Generated by Django 4.0.5 on 2022-06-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0008_country_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.RemoveField(
            model_name='countryvisit',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='countryvisit',
            name='journey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uncle_den_blog_backend.journey', verbose_name='Поездка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('russia', 'Россия'), ('europe', 'Европа'), ('middle-east', 'Ближний Восток'), ('central-asia', 'Центральная Азия'), ('far-east', 'Дальний Восток'), ('africa', 'Африка'), ('australia', 'Австралия'), ('north-america', 'Северная Америка'), ('south-america', 'Южная Америка'), ('etc', 'Другое')], default='etc', max_length=20, verbose_name='Регион'),
        ),
    ]
