# Generated by Django 4.0.5 on 2022-06-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncle_den_blog_backend', '0009_alter_post_options_remove_countryvisit_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='countries',
            field=models.ManyToManyField(to='uncle_den_blog_backend.country', verbose_name='Посещение страны'),
        ),
        migrations.DeleteModel(
            name='CountryVisit',
        ),
    ]
