/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {Fragment, useEffect, useRef, useState} from 'react'
import {useGLTF} from '@react-three/drei'
import {Canvas} from "@react-three/fiber";
import '../../styles/worldmap.css'
import {gsap} from "gsap";

export default function WorldMap(props) {
    const {nodes, materials} = useGLTF('/WorldMap.glb')

    const [selectedRegion, setSelectedRegion] = useState(null)
    const [visibility, setVisibility] = useState(false)

    const group = useRef()
    const canvas = useRef()

    function showRegion(event) {
        setSelectedRegion(event.eventObject.name)
        setVisibility(true)
    }

    function hideRegion() {
        setVisibility(false)
    }

    useEffect(() => {
        if (!props.visibility) {
            gsap.to(canvas.current, {opacity: 0.4, duration: 1})
        } else {
            gsap.to(canvas.current, {opacity: 1})
        }
    }, [props.visibility])

    return (
        <Fragment>
            <RegionStatsBubble region={selectedRegion} visible={props.visibility && visibility}/>
            <Canvas ref={canvas} className={"canvas"}>
                <directionalLight position={[10, 5, 15]} intensity={1.6}/>
                <group ref={group} scale={5.5} position={[-0.6, 0.4, 0]} rotation={[Math.PI / 2.1, 0, 0]} {...props}
                       dispose={null}>
                    <group name={'SouthAmerica'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }}
                           scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002.geometry}
                            material={nodes.Mesh002.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_1.geometry}
                            material={nodes.Mesh002_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_2.geometry}
                            material={nodes.Mesh002_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_3.geometry}
                            material={nodes.Mesh002_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_4.geometry}
                            material={nodes.Mesh002_4.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_5.geometry}
                            material={nodes.Mesh002_5.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_6.geometry}
                            material={nodes.Mesh002_6.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_7.geometry}
                            material={nodes.Mesh002_7.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh002_8.geometry}
                            material={nodes.Mesh002_8.material}
                        />
                    </group>
                    <group name={'Africa'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003.geometry}
                            material={nodes.Mesh003.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003_1.geometry}
                            material={nodes.Mesh003_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003_2.geometry}
                            material={nodes.Mesh003_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003_3.geometry}
                            material={nodes.Mesh003_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003_4.geometry}
                            material={nodes.Mesh003_4.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003_5.geometry}
                            material={nodes.Mesh003_5.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003_6.geometry}
                            material={nodes.Mesh003_6.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh003_7.geometry}
                            material={nodes.Mesh003_7.material}
                        />
                    </group>
                    <group name={'GreatBritain'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh004.geometry}
                            material={nodes.Mesh004.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh004_1.geometry}
                            material={nodes.Mesh004_1.material}
                        />
                    </group>
                    <group name={'Europe'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh005.geometry}
                            material={nodes.Mesh005.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh005_1.geometry}
                            material={nodes.Mesh005_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh005_2.geometry}
                            material={nodes.Mesh005_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh005_3.geometry}
                            material={nodes.Mesh005_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh005_4.geometry}
                            material={nodes.Mesh005_4.material}
                        />
                    </group>
                    <group name={'NearEast'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh006.geometry}
                            material={nodes.Mesh006.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh006_1.geometry}
                            material={nodes.Mesh006_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh006_2.geometry}
                            material={nodes.Mesh006_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh006_3.geometry}
                            material={nodes.Mesh006_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh006_4.geometry}
                            material={nodes.Mesh006_4.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh006_5.geometry}
                            material={nodes.Mesh006_5.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh006_6.geometry}
                            material={nodes.Mesh006_6.material}
                        />
                    </group>
                    <group name={'SouthAsia'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh007.geometry}
                            material={nodes.Mesh007.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh007_1.geometry}
                            material={nodes.Mesh007_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh007_2.geometry}
                            material={nodes.Mesh007_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh007_3.geometry}
                            material={nodes.Mesh007_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh007_4.geometry}
                            material={nodes.Mesh007_4.material}
                        />
                    </group>
                    <group name={'SoutheastAsia'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh008.geometry}
                            material={nodes.Mesh008.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh008_1.geometry}
                            material={nodes.Mesh008_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh008_2.geometry}
                            material={nodes.Mesh008_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh008_3.geometry}
                            material={nodes.Mesh008_3.material}
                        />
                    </group>
                    <group name={'NorthAsia'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh009.geometry}
                            material={nodes.Mesh009.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh009_1.geometry}
                            material={nodes.Mesh009_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh009_2.geometry}
                            material={nodes.Mesh009_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh009_3.geometry}
                            material={nodes.Mesh009_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh009_4.geometry}
                            material={nodes.Mesh009_4.material}
                        />
                    </group>
                    <group name={'Russia'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh010.geometry}
                            material={nodes.Mesh010.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh010_1.geometry}
                            material={nodes.Mesh010_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh010_2.geometry}
                            material={nodes.Mesh010_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh010_3.geometry}
                            material={nodes.Mesh010_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh010_4.geometry}
                            material={nodes.Mesh010_4.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh010_5.geometry}
                            material={nodes.Mesh010_5.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh010_6.geometry}
                            material={nodes.Mesh010_6.material}
                        />
                    </group>
                    <group name={'Australia'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh011.geometry}
                            material={nodes.Mesh011.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh011_1.geometry}
                            material={nodes.Mesh011_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh011_2.geometry}
                            material={nodes.Mesh011_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh011_3.geometry}
                            material={nodes.Mesh011_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh011_4.geometry}
                            material={nodes.Mesh011_4.material}
                        />
                    </group>
                    <group name={'NorthAmerica'}
                           onPointerEnter={(event) => {
                               showRegion(event)
                           }}
                           onPointerLeave={() => {
                               hideRegion()
                           }} scale={[0.03, 0.03, 0.03]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012.geometry}
                            material={nodes.Mesh012.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_1.geometry}
                            material={nodes.Mesh012_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_2.geometry}
                            material={nodes.Mesh012_2.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_3.geometry}
                            material={nodes.Mesh012_3.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_4.geometry}
                            material={nodes.Mesh012_4.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_5.geometry}
                            material={nodes.Mesh012_5.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_6.geometry}
                            material={nodes.Mesh012_6.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_7.geometry}
                            material={nodes.Mesh012_7.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_8.geometry}
                            material={nodes.Mesh012_8.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh012_9.geometry}
                            material={nodes.Mesh012_9.material}
                        />
                    </group>
                    <mesh name={'Greenland'}
                          onPointerEnter={(event) => {
                              showRegion(event)
                          }}
                          onPointerLeave={() => {
                              hideRegion()
                          }}
                          geometry={nodes.Other.geometry}
                          material={nodes.Other.material}
                          position={[0, -0.01, 0]}
                          scale={[0.03, 0.03, 0.03]}
                    />
                </group>
            </Canvas>
        </Fragment>
    )
}

useGLTF.preload('/WorldMap.glb')

const RegionStatsBubble = (props) => {
    let bubble = useRef()

    useEffect(() => {
        if (props.visible) {
            gsap.to(bubble.current, {opacity: 1, duration: 0.8})
        } else {
            gsap.to(bubble.current, {opacity: 0, duration: 1})
        }
    }, [props.visible])

    return (
        <div ref={bubble} className={"map__bubble " + props.region}>
            <h2>{props.region}</h2>
        </div>
    )
}